language: "sh"

sudo: "required"

services:
  - "docker"

branches:
  only:
    - "master"

script:
  - "./build.py"

env:
  global:

    # This forces Python to print everything to stdout/stderr immediately.
    # Otherwise, we've seen issues where all the output from our Travis scripts
    # gets buffered, and only gets printed at the end of the test...
    #
    # ... out of order from the rest of the rest of the output!
    #
    # See also: https://docs.python.org/3/using/cmdline.html#cmdoption-u
    #
    - "PYTHONUNBUFFERED=x"

    # This encrypted environment variable contains the password for the
    # wellcometravis Docker Hub account.  It was obtained by running:
    #
    #     $ travis encrypt PASSWORD=$PASSWORD
    #
    - secure: "dCSO+POxac2245+JFeqvUSHnOTgSFLv6/977+BsO+Fxdy5NQS34U34rFI9zoQ76V00Qcosp+D6RBpCAZmoWaiAB6eAuIfY5fu9NilxSJMEFVXbePc2jWzyYPycp2CC0e/LP8SGZsi5Kv6xA7F87YhfoKrhnIYydLAlYzrtVUhuHCbEDhgpfCL2M09l9jiynPgodAMyS+YnzrRoAEDtcNwvUxyZeQ1CDfTJkI7j9PdUE50lM/MLoliBeNQhH8TSLTs9zTpLCZevIg/1YPHNA0ECQRfRba9Ou4l9Qp1h8oHadzclurNa7g3TDXXOzjHj/1OZlK70EVO7sIybYUyhcUWZN98lc5e2EYXE3o9ihvrSnKxZO3gGZ7qY6JuVw68Sw4dq5PfmWyuoGKW8ekTpGWOQzobjIHG/lc54bKxqsT3tBuGmgtdB1O8xS/3FyvvfYMxqwAoL8giU7Tq6PryNsLvnAC4vW4IxwBrEHxmqGmTTk+LL+spkNqXQNj19I4QoDm4yjdDSueIEufj2aJ06vI1aR/QR55wxVQsGQcD+sa9kGGpcdlsMMy4Q1EhE8Xg/2BLG6+QaRDIR4tYrDQHTVNVe/4k06OFF7c23MadjDlqzFiUuf5lp//AKdqcjYWuJbDgHqOP6l0NtnZbNs8VksHySc9NxLIbYt23ncFs6TKwpE="

notifications:
  email:
    recipients:
      - "wellcomedigitalplatform@wellcome.ac.uk"
